name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          preCommands: |
            npm config set legacy-peer-deps true
            ./prepare.sh
          packageManager: npm
          command: deploy --env production
        env:
          D1_NAME: ${{ secrets.D1_NAME }}
          D1_ID: ${{ secrets.D1_ID }}
          KV_ID: ${{ secrets.KV_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          CUSTOM_DOMAIN: ${{ vars.CUSTOM_DOMAIN }}
          SHARE_MAX_SIZE_IN_MB: ${{ vars.SHARE_MAX_SIZE_IN_MB }}
          SHARE_DURATION: ${{ vars.SHARE_DURATION }}
          RATE_LIMIT: ${{ vars.RATE_LIMIT }}
